

class FindingNotFoundError(Exception):
    pass


class UserNotFoundError(Exception):
    pass


class UserAlreadyExistError(Exception):
    pass
